version: "3.7"
services:
  vault:
    image: vault:1.4.2
    container_name: vault
    hostname: vault
    ports:
      - 8080:8080
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - vault-data:/vault/file/
    environment:
      - VAULT_ADDR=http://localhost:8080
    cap_add:
      - IPC_LOCK
    command: server
    restart: always
    networks:
      - vault_network 

  vault-init:
    image: vault:1.4.2
    container_name: vault-init
    environment:
      - VAULT_ADDR=http://vault:8080
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-test}
    volumes:
      - ./vault-root-token:/vault/file/vault-root-token
      - ./vault-init.sh:/usr/local/bin/vault-init.sh
      - vault-data:/vault/file/
    command: /usr/local/bin/vault-init.sh
    restart: on-failure
    depends_on:
      - vault
    networks:
        - vault_network
  
  portainer:
    # pass: 123456!@#$%^
    image: portainer/portainer-ce:2.19.4
    container_name: portainer
    restart: always
    security_opt:
        - no-new-privileges:true
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./docker-compose/portainer-data:/data
    networks:
        - vault_network
    ports:
    - 9000:9000

networks:
  vault_network:
      driver: bridge

volumes:
  vault-data: